"""Add user table

Revision ID: 121ca0180549
Revises: 
Create Date: 2023-01-31 20:58:25.208989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '121ca0180549'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
