"""Add user table

Revision ID: 832c61a25ee8
Revises: 121ca0180549
Create Date: 2023-01-31 21:03:37.489789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '832c61a25ee8'
down_revision = '121ca0180549'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
